# Generated by Django 6.1.1 on 2026-09-29 15:17

import django.core.validators
import django.db.models.deletion
import market.storages
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='item',
        ),
        migrations.AddField(
            model_name='user',
            name='piger_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='piger 余额'),
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(verbose_name='签到日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'ordering': ['-checkin_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('summary', models.TextField(blank=True, default='', verbose_name='简介')),
                ('content', models.TextField(blank=True, default='', verbose_name='详细说明')),
                ('cost_piger', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='解锁价格')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=12, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='market.category', verbose_name='分类')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='解锁时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='market.work', verbose_name='作品')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PigerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='变动数量')),
                ('balance_after', models.PositiveIntegerField(verbose_name='变动后余额')),
                ('reason', models.CharField(choices=[('register', '注册赠送'), ('checkin', '每日签到'), ('unlock', '解锁作品'), ('admin_grant', '管理员调整')], max_length=20, verbose_name='原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piger_transactions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piger_transactions', to='market.work', verbose_name='相关作品')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='works/%Y/%m/', verbose_name='图片')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.work', verbose_name='作品')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512, verbose_name='项目内路径')),
                ('file', models.FileField(storage=market.storages.PrivateStorage(), upload_to='work-sources/%Y/%m/', verbose_name='源码文件')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('is_text', models.BooleanField(default=False, verbose_name='是否可在线阅读')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='market.work', verbose_name='作品')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
        migrations.AddConstraint(
            model_name='checkin',
            constraint=models.UniqueConstraint(fields=('user', 'checkin_date'), name='unique_daily_checkin'),
        ),
        migrations.AddConstraint(
            model_name='unlock',
            constraint=models.UniqueConstraint(fields=('user', 'work'), name='unique_user_work_unlock'),
        ),
        migrations.AddConstraint(
            model_name='worksourcefile',
            constraint=models.UniqueConstraint(fields=('work', 'path'), name='unique_work_source_path'),
        ),
    ]
