# Generated by Django 6.1.1 on 2026-09-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_remove_itemimage_item_user_piger_balance_checkin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ['-checkin_date', '-id'], 'verbose_name': '签到记录', 'verbose_name_plural': '签到记录'},
        ),
        migrations.AlterModelOptions(
            name='pigertransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'piger 流水', 'verbose_name_plural': 'piger 流水'},
        ),
        migrations.AlterModelOptions(
            name='unlock',
            options={'ordering': ['-created_at'], 'verbose_name': '解锁记录', 'verbose_name_plural': '解锁记录'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-created_at'], 'verbose_name': '作品', 'verbose_name_plural': '作品'},
        ),
        migrations.AlterModelOptions(
            name='workimage',
            options={'ordering': ['uploaded_at'], 'verbose_name': '作品图片', 'verbose_name_plural': '作品图片'},
        ),
        migrations.AlterModelOptions(
            name='worksourcefile',
            options={'ordering': ['path'], 'verbose_name': '源码文件', 'verbose_name_plural': '源码文件'},
        ),
    ]
