# Generated by Django 6.1.1 on 2026-09-30 04:55

from django.db import migrations, models


def add_default_tags(apps, schema_editor):
    Tag = apps.get_model("market", "Tag")
    Work = apps.get_model("market", "Work")
    tag = Tag.objects.filter(name="未分类").first()
    if tag is None:
        tag = Tag.objects.create(name="未分类")
    for work in Work.objects.all():
        if not work.tags.exists():
            work.tags.add(tag)


def remove_default_tags(apps, schema_editor):
    Tag = apps.get_model("market", "Tag")
    Work = apps.get_model("market", "Work")
    tag = Tag.objects.filter(name="未分类").first()
    if tag is None:
        return
    for work in Work.objects.all():
        work.tags.remove(tag)
    if not tag.users.exists() and not tag.works.exists():
        tag.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_category_options_alter_checkin_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='一句话介绍'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', to='market.tag', verbose_name='技能标签'),
        ),
        migrations.AddField(
            model_name='work',
            name='tags',
            field=models.ManyToManyField(related_name='works', to='market.tag', verbose_name='作品标签'),
        ),
        migrations.RunPython(add_default_tags, remove_default_tags),
    ]
