# Generated by Django 6.1.1 on 2026-09-30 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_rename_default_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('changelog', models.TextField(blank=True, default='', verbose_name='更新说明')),
                ('released_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='market.work', verbose_name='作品')),
            ],
            options={
                'verbose_name': '版本更新',
                'verbose_name_plural': '版本更新',
                'ordering': ['-released_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('work', 'version'), name='unique_work_version')],
            },
        ),
    ]
